openapi: 3.0.0
info:
  title: CKCPhoneStore API
  description: |
    Document cho API của ứng dụng bán điện thoại di động CKC Phone Store

    _Tác giả: Đoàn Văn Quốc_
  version: 1.0.0
servers:
  # - url: http://localhost:3000/
  - url: https://ckc-api.onrender.com/
tags:
  - name: auth
    description: Các API liên quan đến đăng nhập và đăng ký
  - name: user
    description: Các API liên quan đến user
paths:
  /auth/login:
    post:
      tags:
        - "auth"
      summary: Đăng nhập tài khoản
      description: Đăng nhập tài khoản người dùng.
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: 'trananhqunan'
              password: '123456'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              example:
                - mesage: Đăng nhập thành công
                  username: admin
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlhdCI6MTcwNDkwMTg1NiwiZXhwIjoxNzA0OTAxOTE2fQ.vimknPL9V2WdyS2lLUlhyBe1T-YeFOQElo0DH5Qz23k
  /auth/register:
    post:
      tags:
        - "auth"
      summary: Tạo người dùng mới
      description: Tạo một người dùng mới với thông tin cung cấp.
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: 'admin4'
              password: '123456'
              fullname: 'Admin4'
      responses:
        '201':
          description: Người dùng mới đã được tạo thành công
          content:
            application/json:
              example:
                - message: Tạo user mới thành công
  /user:
    get:
      tags:
        - "user"
      summary: Lấy thông tin user dựa trên token
      parameters:
        - name: token
          in: query
          description: User token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - message: Thành công
                  user:
                    username: admin
                    fullname: Doan Van Quoc


  # /users/{userId}:
  #   parameters:
  #     - name: userId
  #       in: path
  #       description: ID của người dùng
  #       required: true
  #       schema:
  #         type: integer
  #   get:
  #     summary: Lấy thông tin chi tiết của một người dùng
  #     responses:
  #       '200':
  #         description: Thông tin chi tiết của người dùng đã được trả về thành công
  #         content:
  #           application/json:
  #             example:
  #               id: 1
  #               name: John Doe
