openapi: 3.0.0
info:
  title: CKCPhoneStore API
  description: |
    Document cho API của ứng dụng bán điện thoại di động CKC Phone Store

    _Tác giả: Đoàn Văn Quốc_
  version: 1.0.0
servers:
  # - url: http://localhost:3000/
  - url: https://api.vanquoc.id.vn/
tags:
  - name: auth
    description: Các API liên quan đến đăng nhập và đăng ký
  - name: user
    description: Các API liên quan đến user
paths:
  /auth/login:
    post:
      tags:
        - "auth"
      summary: Đăng nhập tài khoản
      description: Đăng nhập tài khoản người dùng.
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: 'admin@gmail.com'
              password: '123456'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              example:
                - mesage: Đăng nhập thành công
                  userID: 1
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlhdCI6MTcwNDkwMTg1NiwiZXhwIjoxNzA0OTAxOTE2fQ.vimknPL9V2WdyS2lLUlhyBe1T-YeFOQElo0DH5Qz23k
  /auth/register:
    post:
      tags:
        - "auth"
      summary: Tạo người dùng mới
      description: Tạo một người dùng mới với thông tin cung cấp.
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: 'vanquoc@gmail.com'
              password: '123456'
              fullname: 'Admin4'
              birthday: 2003-06-27
              phoneNumber: '0388780055'
              avatar: https://randomuser.me/api/portraits/men/9.jpg
      responses:
        '201':
          description: Người dùng mới đã được tạo thành công
          content:
            application/json:
              example:
                - message: Tạo user mới thành công
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJhZG1pbjNAZ21haWwuY29tIiwiZnVsbG5hbWUiOiJhYmMiLCJiaXJ0aGRheSI6IjIwMDMtMDYtMjdUMDA6MDA6MDAuMDAwWiIsInBob25lTnVtYmVyIjoiMDM4ODc4MDAwMSIsImF2YXRhciI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi85MTBqcGciLCJpYXQiOjE3MDUxMzQ3MzMsImV4cCI6MTcwNTEzNDc5M30.g-68vG7rIPSN91K3gTcLx_BC9iHB1tvGk_cP4gJIsc8
  /user/{id}:
    get:
      tags:
        - "user"
      summary: Lấy thông tin user dựa trên id
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - message: Thành công
                  data:
                    id: 1
                    email: admin@gmail.com
                    fullname: Doan Van Quoc
                    birthday: 2003-06-27
                    phoneNumber: '0388780052'
                    avatar: https://randomuser.me/api/portraits/men/9.jpg


  # /users/{userId}:
  #   parameters:
  #     - name: userId
  #       in: path
  #       description: ID của người dùng
  #       required: true
  #       schema:
  #         type: integer
  #   get:
  #     summary: Lấy thông tin chi tiết của một người dùng
  #     responses:
  #       '200':
  #         description: Thông tin chi tiết của người dùng đã được trả về thành công
  #         content:
  #           application/json:
  #             example:
  #               id: 1
  #               name: John Doe
